export const DEPARTMENT_OPTIONS: string[] = [
  'Engineering',
  'Product',
  'Design',
  'Quality Assurance',
  'Human Resources',
  'Sales',
  'Marketing',
  'Finance',
  'Operations',
  'Customer Support',
  'IT / DevOps',
  'Administration',
  'Legal',
  'Business Development',
];

export const JOB_TITLE_OPTIONS: string[] = [
  'Software Engineer',
  'Senior Software Engineer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'QA Engineer',
  'UI/UX Designer',
  'Product Manager',
  'Project Manager',
  'Business Analyst',
  'DevOps Engineer',
  'Team Lead',
  'HR Executive',
  'HR Manager',
  'Manager',
  'Director',
  'Administrator',
  'Intern',
];
